version: '3'
services:
  bot:
    build: .
    environment:
      HUGGING_FACE_MODEL: ${HUGGING_FACE_MODEL}
      HUGGING_FACE_TOKEN: ${HUGGING_FACE_TOKEN}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DEBUG: ${DEBUG}
    restart: always